name: Coverage

on:
  push:
    paths:
      - 'src/**/*.ts'
      - '__tests__/**/*.ts'
      - 'package.json'
      - '.github/workflows/coverage.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 'v16.x'
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn coverage
      - name: Send coverage info to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/cobertura-coverage.xml
